import jsPDF from 'jspdf';

// AAAA Problem: JS PDF default font doesn't support Japanese. 
// Detailed solution: jsPDF needs a base64 font string added. 
// For this environment, downloading a font file and converting to base64 is hard.
// Alternative: Use a CDN or try to use a font that is available? No, jsPDF creates PDF client side, needs font data.
// Workaround: We will use a very simple approach or try to fetch a font if possible?
// OR: We can't easily do Japanese PDF client side without a large font file.
// Strategy Change: The user requirements said "PDF download".
// If I can't bundle a 5MB font file easily, I might use HTML2Canvas + jsPDF? 
// That converts the DOM to image then puts in PDF. This supports Japanese easily as it renders what the browser sees.

export const generatePDF = (data) => {
  // data: { problem, topic, result, all_answers }

  // Format current date
  const dateStr = new Date().toLocaleDateString('ja-JP');

  // Build HTML Content
  const htmlContent = `
    <html>
      <head>
        <title>Oogiri Jam Report - ${dateStr}</title>
        <style>
          body { font-family: sans-serif; padding: 40px; color: #333; max-width: 800px; mx-auto; }
          h1 { font-size: 24px; border-bottom: 2px solid #ccc; padding-bottom: 10px; margin-bottom: 20px; }
          h2 { font-size: 18px; background: #eee; padding: 5px; margin-top: 20px; }
          p { font-size: 16px; margin: 5px 0; }
          .section { margin-bottom: 20px; }
          .awards { display: flex; gap: 20px; }
          .award-box { flex: 1; border: 1px solid #ddd; padding: 15px; border-radius: 8px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th { background: #f9fafb; border: 1px solid #ddd; padding: 8px; text-align: left; }
          td { border: 1px solid #ddd; padding: 8px; vertical-align: top; }
          .tsukkomi { color: #d97706; font-weight: bold; margin-bottom: 4px; }
          .pivot { color: #059669; font-size: 0.9em; }
          @media print {
            .no-print { display: none; }
            body { padding: 0; }
          }
        </style>
      </head>
      <body>
        <h1>Oogiri Jam - Report (${dateStr})</h1>
        
        <div class="section">
          <h2>【ビジネス課題】</h2>
          <p>${data.problem || 'N/A'}</p>
        </div>

        <div class="section">
          <h2>【採用された大喜利お題】</h2>
          <p>${data.topic || 'N/A'}</p>
        </div>

        <div class="section">
          <h2>【グランプリ & ピボット賞】</h2>
          <div class="awards">
            <div class="award-box" style="border-color: #fbbf24; background: #fffbeb;">
              <h3 style="color: #d97706; margin-top:0;">🏆 グランプリ</h3>
              <p><strong>受賞者:</strong> ${data.result?.grand_prix?.nickname || '-'}</p>
              <p><strong>回答:</strong> ${data.result?.grand_prix?.deviation || '-'}</p>
              <p style="font-size: 0.8em; color: #666; margin-top: 10px;">${data.result?.grand_prix?.reason || '-'}</p>
            </div>
            <div class="award-box" style="border-color: #3b82f6; background: #eff6ff;">
              <h3 style="color: #2563eb; margin-top:0;">💡 ピボット賞</h3>
              <p><strong>受賞者:</strong> ${data.result?.pivot_award?.nickname || '-'}</p>
              <p><strong>回答:</strong> ${data.result?.pivot_award?.deviation || '-'}</p>
              <p style="font-size: 0.8em; color: #666; margin-top: 10px;">${data.result?.pivot_award?.reason || '-'}</p>
            </div>
          </div>
        </div>

        <div class="section">
          <h2>【全回答リスト】</h2>
          <table>
            <thead>
              <tr>
                <th>ニックネーム</th>
                <th>回答 (ボケ)</th>
                <th>AI評価</th>
              </tr>
            </thead>
            <tbody>
              ${(data.all_answers || []).map(a => `
                <tr>
                  <td>${a.nickname}</td>
                  <td>${a.deviation}</td>
                  <td>
                    <div class="tsukkomi">${a.tsukkomi || ''}</div>
                    <div class="pivot">→ ${a.business_pivot || ''}</div>
                  </td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>

        <div style="text-align: right; margin-top: 30px; font-size: 12px; color: #999;">
          Generated by Oogiri Jam
        </div>

        <script>
          window.onload = () => {
             // Automatically trigger print
             window.print();
             // Optional: Close after print (commented out to let user check)
             // window.onafterprint = () => window.close();
          }
        </script>
      </body>
    </html>
  `;

  // Open in new window
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close(); // Finish writing
  } else {
    alert("ポップアップがブロックされました。許可してください。");
  }
};
